[package]
name = "rust-buck3t-ui"
version = "0.0.1"
edition = "2021"

[dependencies]
actix-web = "*"
actix-files = "*"
serde = { version = "*", features = ["derive"] }
reqwest = { version = "*", features = ["json"] }
serde_json = "1"
dotenvy = "0.15"